### ISSUE TITLE
UI UX improvements

### ISSUE THREAD

**Issue by jasco** [KnowikiApps/scale-conf-app#12]
Version 1.3

- Add margins, padding.
- Consider options for decluttering or minimizing visual noise.
- Consider long click or line item drawers as option for bookmarking.
- Alternate views, such as time focus, topic focus,  etc. Perhaps tie into larger filter feature, but views might provide subsets of info based on purpose. 
- Search. By text, speaker, etc
- Speaker list 
- Help with discovery. Consider feedback mechanism. Live reviews?

**Comment by KnowikiApps** [comment]
I'm going to close this one because all of these items seem to be addressed in their own respective issues.
