### ISSUE TITLE
Rework build system for Android or document steps needed to deploy.

### ISSUE THREAD

**Issue by 42flyingfish** [KnowikiApps/scale-conf-app#30]
As shown at SCALE 2022, we had to preforms special actions to get the project to build and deploy for Android. Examples include the android manifest being mostly ignored, editing a template file to include the app name, and occasional missing icons. These special steps either need to be documented or we need to dive in and find a better solution.

**Comment by KnowikiApps** [comment]
I have figured out some of the issues. I know last time the build system was ignoring the AndroidManifest.xml file and that seems to have been fixed. Android has changed some of the build requirements for the store so I'm updating this in real time for 20x

**Comment by KnowikiApps** [comment]
reworked with the new CI pipeline runner
