### ISSUE TITLE
Campus Map is blank

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#46]
Campus Map is blank.

Tested on android.

**Comment by KnowikiApps** [comment]
This page has what we need for this. https://www.visitpasadena.com/convention-center/planners/facility-map/

There are a few ways we can solve this I think:

Worst case we screenshot the web page and embed the image into the app on the next build

Another option is to convert the page to a webview pointed at the url. Just like some of the other pages. We can also run Javascript injections on the page to alter the functionality or appearance.

**Comment by jaymzh** [comment]
I vote we use a webview. It seems the most flexible and easiest. Are there any downsides to that?

**Comment by KnowikiApps** [comment]
Not any downsides I can think of. We can duplicate this page

https://github.com/KnowikiApps/scale-conf-app/blob/master/qml/pages/Exhibitors/Exhibitors.qml
