### ISSUE TITLE
Schedule loading is misleading

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#47]
Schedule appears to be blank. Much later, it's populated, Probably need a "loading" text/image.

**Comment by jaymzh** [comment]
This one - it took almost 3 minutes for anything to load on the schedule. That's really bad. Can we partial load? Something?

**Comment by KnowikiApps** [comment]
This is probably the backend booting up. We're on a free tier hosting and its kinda slow. If it gets to be enough of an issue I can bump up to a paid tier for the conference.

The loading feature was something we had talked about before so this is related to issue #20

**Comment by jaymzh** [comment]
Yeah this one feels especially bad for me. I don't care so much if it takes a while since it seems to keep it locally once it has it - but if it doesn't SAY, "hey this take a minute", it feels like a bug and like it'll never load and most people are likely to just not use the app at that point.
