### ISSUE TITLE
On the Exhibitors page, the menu and top bar are obscured

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#49]
On the Exhibitors page, the menu and top bar are obscured

**Comment by jaymzh** [comment]
This is... half fixed. Now the hamburger menu on the left is gone, and the arrow is over it.

**Comment by KnowikiApps** [comment]
Set the visibility of the hamburger menu when the page loads. Check here:

https://github.com/KnowikiApps/scale-conf-app/blob/6703871a8f3352ed5e62bcdf1b1df64f9bc3414c/qml/components/navigation/TopBar.qml#L22
