### ISSUE TITLE
Menu button for the "announcements" page

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#51]
The menu should have a button for the "announcements" page, IMO

**Comment by KnowikiApps** [comment]
This is a boolean visibility setting for the object. We need to make sure to set it properly when the page loads. Check here
https://github.com/KnowikiApps/scale-conf-app/blob/6703871a8f3352ed5e62bcdf1b1df64f9bc3414c/qml/components/navigation/TopBar.qml#L22
