### ISSUE TITLE
Android: no icon

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#52]
The app on android has the default Droid icon instead of the SCALE icon.

**Comment by irabinovitch** [comment]
Can we use the new SCALE logo? https://github.com/socallinuxexpo/SCALE-Planning/tree/master/branding/logos

**Comment by jaymzh** [comment]
There's an icon, but it's MICROMINI. There's a square icon inside the circle icon and  then our icon is inside that.
