### ISSUE TITLE
Weird nav bug

### ISSUE THREAD

**Issue by jaymzh** [KnowikiApps/scale-conf-app#54]
From Kyle_t:

If you complete the following steps... Hamburger menu -> Contacts -> Tap "Scan Badge" -> Hamburger menu -> "Exhibitors" or "Special Events" -> Back button... The "Exhibitors" or "Special Events" content does not get removed, and I am unable to navigate the app without restarting it

Possibly IOS only.

**Comment by KyleTownsend74** [comment]
This line may be cause for bug: https://github.com/KnowikiApps/scale-conf-app/blob/master/qml/pages/Contacts/Contacts.qml#L49
